name: SpaceStatistics
version: @version@
main: dev.spaceseries.spacestatistics.SpaceStatistics
api-version: 1.16
authors: [ yakovliam ]
description: Statistics management plugin that is implemented as an API
website: https://www.yakovliam.com/
